[package]
name = "herbs_http"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
openssl = { version = "0.10" }
chrono = "0.4.38"
mongodb = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
uuid = "1.10.0"
